#pragma once
#include <Windows.h>

#define DEFS_UNIQUE_ID         L"7E6C959EAA304D46BDB14E12F895B29B"
#define DEFS_APPLICATION_NAME  L"AutoPlay"
#define DEFS_WINDOW_CLASS_NAME DEFS_UNIQUE_ID DEFS_APPLICATION_NAME
#define DEFS_WINDOW_WIDTH      400
#define DEFS_WINDOW_HEIGHT     400

#define DEFS_RESID_WAVE1  100
#define DEFS_RESID_TIMER1 101
